name: Deploy Working

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.3'
          channel: 'stable'
          
      - name: Fix Dependencies
        run: |
          # Downgrade flutter_lints to compatible version
          sed -i 's/flutter_lints: ^5.0.0/flutter_lints: ^3.0.0/' pubspec.yaml
          
          # Get dependencies
          flutter pub get
          
      - name: Build Web
        run: |
          # Build with minimal optimizations
          flutter build web --release --web-renderer html --dart-define=Dart2jsOptimization=O1
          
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          force_orphan: true