name: Deploy Debug

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'
          channel: 'stable'
          
      - name: Debug Info
        run: |
          flutter --version
          dart --version
          flutter doctor -v
          
      - name: Get Dependencies with verbose
        run: |
          flutter pub get --verbose
          
      - name: Disable Lints and Analysis
        run: |
          # Create analysis options to disable all lints
          cat > analysis_options.yaml << 'EOF'
          analyzer:
            errors:
              todo: ignore
              deprecated_member_use: ignore
              deprecated_member_use_from_same_package: ignore
              invalid_annotation_target: ignore
              undefined_prefixed_name: ignore
            exclude:
              - "**/*.g.dart"
              - "**/*.freezed.dart"
          
          linter:
            rules:
          EOF
          
      - name: Build Web (No analysis)
        run: |
          flutter build web --release --web-renderer html --no-pub --verbose || (
            echo "Build failed, trying with dart2js options..."
            flutter build web --release --web-renderer html --no-pub --dart2js-optimization O1
          )
          
      - name: If build failed, try emergency build
        if: failure()
        run: |
          echo "Trying emergency build without optimizations..."
          flutter build web --debug --web-renderer html
          
      - uses: JamesIves/github-pages-deploy-action@v4
        if: success()
        with:
          folder: build/web