name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'
          channel: 'stable'
          
      - name: Fix Dependencies
        run: |
          # Downgrade flutter_lints to stable compatible version
          sed -i 's/flutter_lints: ^6.0.0/flutter_lints: 4.0.0/' pubspec.yaml
          
      - name: Build Web App
        run: |
          flutter --version
          flutter pub get
          flutter build web --release --web-renderer html --base-href /owaspnote/
      - name: Prepare deployment
        run: |
          # Create .nojekyll file to prevent Jekyll processing
          touch build/web/.nojekyll
          # List files to verify
          ls -la build/web/
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          force_orphan: true
          cname: false
