name: Deploy Minimal

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'
          
      - name: Quick Build
        run: |
          # Remove flutter_lints temporarily
          sed -i '/flutter_lints:/d' pubspec.yaml
          
          # Get dependencies
          flutter pub get
          
          # Build
          flutter build web --release
          
      - name: Upload to Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/web
          
      - name: Deploy
        uses: actions/deploy-pages@v4